var countiesDict = {"36091":["AL","Autauga County"],
"36758":["AL","Autauga County"],
"36006":["AL","Autauga County"],
"36067":["AL","Autauga County"],
"36701":["AL","Autauga County"]
 };


var stateObject = {
    "Alabama": "al",
   "Alaska":"ak",
   "American Samoa":"as",
   "Arizona":"az",
   "Arkansas":"ar",
   "California":"ca",
   "Colorado":"co",
   "Connecticut":"ct",
   "Delaware":"de",
   "District of Columbia":"dc",
   "Florida":"fl",
   "Georgia":"ga",
   "Guam":"gu",
   "Hawaii":"hi",
   "Idaho":"id",
   "Illinois":"il",
   "Indiana":"in",
   "Iowa":"ia",
   "Kansas":"ks",
   "Kentucky":"ky",
   "Louisiana":"la",
   "Maine":"me",
   "Maryland":"md",
   "Massachusetts":"ma",
   "Michigan":"mi",
   "Minnesota":"mn",
   "Mississippi":"ms",
   "Missouri":"mo",
   "Montana":"mt",
   "Nebraska":"ne",
   "Nevada":"nv",
   "New Hampshire":"nh",
   "New Jersey":"nj",
   "New Mexico":"nm",
   "New York":"ny",
   "North Carolina":"nc",
   "North Dakota":"nd",
   "Northern Mariana is":"mp",
   "Ohio":"oh",
   "Oklahoma":"ok",
   "Oregon":"or",
   "Pennsylvania":"pa",
   "Puerto Rico":"pr",
   "Rhode Island":"ri",
   "South Carolina":"sc",
   "South Dakota":"sd",
   "Tennessee":"tn",
   "Texas":"tx",
   "Utah":"ut",
   "Vermont":"vt",
   "Virgin islands":"vi",
   "Virginia":"va",
   "Washington":"wa",
   "West Virginia":"wv",
   "Wisconsin":"wi",
   "Wyoming":"wy"
};

var stateAbbrevObject = {
    "AL": "Alabama",
    "AK":"Alaska",
    "AS":"American Samoa",
    "AZ":"Arizona",
    "AR":"Arkansas",
    "CA":"California",
    "CO":"Colorado",
    "CT":"Connecticut",
    "DE":"Delaware",
    "DC":"District of Columbia",
    "FL":"Florida",
    "GA":"Georgia",
    "GU":"Guam",
    "HI":"Hawaii",
    "ID":"Idaho",
    "IL":"Illinois",
    "IN":"Indiana",
    "IA":"Iowa",
    "KS":"Kansas",
    "KY":"Kentucky",
    "LA":"Louisiana",
    "ME":"Maine",
    "MD":"Maryland",
    "MA":"Massachusetts",
    "MI":"Michigan",
    "MN":"Minnesota",
    "MS":"Mississippi",
    "MO":"Missouri",
    "MT":"Montana",
    "NE":"Nebraska",
    "NV":"Nevada",
    "NH":"New Hampshire",
    "NJ":"New Jersey",
    "NM":"New Mexico",
    "NY":"New York",
    "NC":"North Carolina",
    "ND":"North Dakota",
    "MP":"Northern Mariana is",
    "OH":"Ohio",
    "OK":"Oklahoma",
    "OR":"Oregon",
    "PA":"Pennsylvania",
    "PR":"Puerto Rico",
    "RI":"Rhode Island",
    "SC":"South Carolina",
    "SD":"South Dakota",
    "TN":"Tennessee",
    "TX":"Texas",
    "UT":"Utah",
    "VT":"Vermont",
    "VI":"Virgin islands",
    "VA":"Virginia",
    "WA":"Washington",
    "WV":"West Virginia",
    "WI":"Wisconsin",
    "WY" : "Wyoming"
};

var monthsObject = {
    "01": "January",
    "02": "February",
    "03": "March",
    "04": "April",
    "05": "May",
    "06": "June",
    "07": "July",
    "08": "August",
    "09": "September",
    "10": "October",
    "11": "November",
    "11": "December"
};

module.exports.countiesDict = countiesDict;
module.exports.stateObject = stateObject;
module.exports.stateAbbrevObject = stateAbbrevObject;
module.exports.monthsObject = monthsObject;
